2023 10 16 notes
BarbzCodez/Spendr pull request #76
Opened 2023-10-16 20:25 UTC by lysackm

2023-10-16 20:43 UTC, dlarocque requested changes

2023-10-16 20:43 UTC, dlarocque commented on documentation/meeting-logs/2023-10-16.md
> +- When should dan work on the expenses PR?
```suggestion
- When should dan review the expenses PR?
```

2023-10-16 20:43 UTC, dlarocque commented on documentation/meeting-logs/2023-10-16.md
> +  - Since Barbra and Victoria are working on separate things now they can work efficiently
```suggestion
  - Since Barbara and Victoria are working on separate things now they can work efficiently
```

2023-10-16 20:43 UTC, dlarocque commented on documentation/meeting-logs/2023-10-16.md
> +- needed to get the secrets from github
Could we add the updates from the whole team?

We only have your update and Victorias, could we add updates from ethan, barbara and I?

```suggestion
- Ethan finished the express logging and prisma model for our database for all features.
- Barbara got the initial UI for viewing the expenses and user settings, and is now working on integrating user settings UI with the Express API.
- Daniel finished express API for auth and expenses with full code coverage, fixed the docker issues, created CI workflow, and sequence diagrams.
- Victoria finished registration, login, logout in the frontend with full integration, and is now working on the Expenses UI and integration (add, edit, delete, list).
- Mark is working on CD worfklow to automatically build and publish the Docker images to Docker Hub with GitHub Actions- needs to get the secrets from GitHub
```

2023-10-19 14:58 UTC, dlarocque approved these changes

2023-10-19 16:01 UTC, BarbzCodez commented on documentation/meeting-logs/2023-10-16.md
> +- Victoria finished registration, login, logout in the frontend with full integration, and is now working on the Expenses UI and integration (add, edit, delete, list). (https://github.com/BarbzCodez/
```suggestion
- Barbara got the initial UI for viewing the expenses and user settings, and is now working on integrating user settings UI with the Express API. 
   - Change Username, Password and Delete account (https://github.com/BarbzCodez/Spendr/issues/23)
   - History List (Just UI): (https://github.com/BarbzCodez/Spendr/issues/27)
- Daniel finished express API for auth and expenses with full code coverage, fixed the docker issues, created CI workflow, and sequence diagrams. 
   - System Design: (https://github.com/BarbzCodez/Spendr/issues/8)
   - CI setup: (https://github.com/BarbzCodez/Spendr/issues/12)
   - Filtering: (https://github.com/BarbzCodez/Spendr/issues/25)
   - Expenses API: (https://github.com/BarbzCodez/Spendr/issues/52) 
- Victoria finished registration, login, logout in the frontend with full integration, and is now working on the Expenses UI and integration (add, edit, delete, list). 
   - Login: (https://github.com/BarbzCodez/Spendr/issues/21) 
   - Expense History List: (https://github.com/BarbzCodez/Spendr/issues/27)
   - Expense History: (https://github.com/BarbzCodez/Spendr/issues/28)
   - Add Expense: (https://github.com/BarbzCodez/Spendr/issues/26) 
   - Edit Expense: (https://github.com/BarbzCodez/Spendr/issues/60) 
   - Delete Expense: (https://github.com/BarbzCodez/Spendr/issues/61)
```

Just to show actual issues of what we discussed

2023-10-20 03:47 UTC, VictoriaKGN approved these changes
LGTM

2023-10-20 03:56 UTC, merged